<?php

declare(strict_types=1);

namespace MbhSoftware\Treehide\ContextMenu;

use TYPO3\CMS\Backend\ContextMenu\ItemProviders\PageProvider;
use TYPO3\CMS\Core\Configuration\ExtensionConfiguration;
use TYPO3\CMS\Core\Schema\TcaSchemaFactory;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Class ItemProvider
 */
class ItemProvider extends PageProvider
{
    protected $itemsConfiguration = [
        'hidePagesRecursive' => [
            'type'           => 'item',
            'label'          => 'LLL:EXT:treehide/Resources/Private/Language/locallang.xlf:hideRecursive',
            'iconIdentifier' => 'actions-edit-hide',
            'callbackAction' => 'hidePagesRecursive',
        ],
        'unhidePagesRecursive' => [
            'type'           => 'item',
            'label'          => 'LLL:EXT:treehide/Resources/Private/Language/locallang.xlf:unhideRecursive',
            'iconIdentifier' => 'actions-edit-unhide',
            'callbackAction' => 'hidePagesRecursive',
        ],
    ];

    protected bool $allowForNonAdmin = false;
    public function __construct(private readonly TcaSchemaFactory $tcaSchemaFactory)
    {
        parent::__construct();
    }

    protected function initialize()
    {
        parent::initialize();
        $this->allowForNonAdmin = (bool)GeneralUtility::makeInstance(ExtensionConfiguration::class)
            ->get('treehide', 'allowForNonAdmin');
    }

    /**
     * This method adds custom item to list of items generated by item providers with higher priority value (PageProvider)
     * You could also modify existing items here.
     * The new item is added after the 'info' item.
     *
     * @param array $items
     * @return array
     */
    public function addItems(array $items): array
    {
        $this->initialize();
        $this->initDisabledItems();
        $localItems = $this->prepareItems($this->itemsConfiguration);
        if (isset($items['more']['childItems'])) {
            $items['more']['childItems'] = $items['more']['childItems'] + $localItems;
        } else {
            $items += $localItems;
        }
        return $items;
    }

    /**
     * Returns the provider priority which is used for determining the order in which providers are processing items
     * to the result array. Highest priority means provider is evaluated first.
     *
     * BEWARE: Returned priority should logically not clash with another provider.
     *         Please check @return int
     * @see \TYPO3\CMS\Backend\ContextMenu\ContextMenu::getAvailableProviders() if needed.
     */
    public function getPriority(): int
    {
        return 90;
    }

    /**
     * @param string $itemName
     * @return array|string[]
     */
    protected function getAdditionalAttributes(string $itemName): array
    {
        return [
            'data-callback-module' => '@mbhsoft/treehide/ContextMenuActions',
            'data-mode' => $itemName === 'hidePagesRecursive' ? 1 : 0,
        ];
    }

    /**
     * This method is called for each item this provider adds and checks if given item can be added
     *
     * @param string $itemName
     * @param string $type
     * @return bool
     */
    protected function canRender(string $itemName, string $type): bool
    {
        /**
         * check if disabled via user TSconfig, e.g.
         * options.contextMenu.table.pages.tree.disableItems = hidePagesRecursive,unhidePagesRecursive
         * options.contextMenu.table.pages.disableItems = hidePagesRecursive,unhidePagesRecursive
         *
         * @see https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/UserTsconfig/Options.html#confval-useroptions-contextmenu-key-disableitems
         */
        if (in_array($itemName, $this->disabledItems, true)) {
            return false;
        }
        if (!$this->currentUserHasPermissions()) {
            return false;
        }
        // enabled if non-admin enabled (via Extension Configuration) or is admin
        return $this->allowForNonAdmin || $this->backendUser->isAdmin();
    }

    /**
     * This checks if current BE user generelly has permissions to modify pages.hidden,
     * it does not check permissions for a particular page.
     * @return bool
     */
    protected function currentUserHasPermissions(): bool
    {
        if ($this->backendUser->isAdmin()) {
            return true;
        }
        $table = 'pages';
        $field = $GLOBALS['TCA']['pages']['ctrl']['enablecolumns']['disabled'] ?? '';

        if ($this->backendUser->check('tables_modify', $table)) {
            // table not allowed
            return false;
        }
        if (!$this->tcaSchemaFactory->has($table)) {
            return false;
        }
        $schema = $this->tcaSchemaFactory->get($table);

        if (!$schema->hasField($field)) {
            return false;
        }
        $field = $schema->getField($field);
        if ($field->supportsAccessControl()
            && !$this->backendUser->check('non_exclude_fields', $table . ':' . $field->getName())) {
            return false;
        }

        return true;
    }
}
